### PR TITLE
Ported build from oasis to jbuilder.

### PR DESCRIPTION
**Pull request by kc284**
@talex5 as author of this commit https://github.com/xapi-project/ocaml-crc/commit/a1a0bc64cc38a115424e6184d77d35b49f73db94 could you also review this PR and let us know if it still does what you need. Thank.

### CODE REVIEW

**Comment by talex5** [comment]
I don't recall doing anything with this project. I guess the commit is based on a similar patch I made to other projects and so @hannesm tagged me as the author. I don't know how Xen cstubs are supposed to work with jbuilder. I think @avsm mentioned some discussion at ICFP this year in the last Mirage IRC chat.

**Comment by gaborigloi** [comment]
Fixes https://github.com/xapi-project/ocaml-crc/issues/25

**Comment by mseri** [comment]
Looks good to me. Pending on the permissions being fixed and comments from @hannesm and @avsm

**Comment by hannesm** [comment]
thank you very much for notifying me.  `crc` used to be a dependency of [git](https://github.com/mirage/ocaml-git) (until 1.9.2), but has been replaced (in https://github.com/mirage/ocaml-git/pull/166) by a pure OCaml implementation of crc to ease porting (KVM, JavaScript, ..).  This means (a) your build system could be simplified, and not deal with any of this cross-compilation and (b) since I phased out my xen hardware, I cannot test this easily.

**Comment by mseri** [comment]
To have the coverage working you need to inject the `(pps (bisect_ppx))` preprocessor in the jbuild file. See https://github.com/xapi-project/xcp-idl/pull/174/files#diff-a836467651dba6d04fb6ebd8f8b8bf34R21

**Comment by mseri** [comment]
You need to add the bisect stuff also to the main library `jbuild` otherwise it is not considered in the coverage count

**Pull request merged**
