### PR TITLE
add xen_linkopts XMETAExtraLines for xen-via-mirage users

### PR DESCRIPTION
**Pull request by yomimono**
These extra tags are required to use ocaml-crc with MirageOS unikernels.

### CODE REVIEW

**Comment by johnelse** [comment]
Well the tests pass so fine by me :D

**Comment by hannesm** [comment]
@johnelse thanks! if you could now make a release of crc to opam, that'd be great! :)

**Comment by hannesm** [comment]
(but otoh, I'm not sure whether this actually results in a working library, someone should check that -- it doesn't do the xen CFLAGS juggling (`-mno-red-zone`))

**Comment by johnelse** [comment]
Is there a sensible way of getting travis to test this (at least the build)? I don't want to break it :)

Let me know when this is ready and I'll make a release.

**Comment by hannesm** [comment]
This patch from @talex5 looks more complete https://github.com/talex5/ocaml-crc/commit/7b7c59734ec3a1c7b5a0e6c4f5096edfdae2dd33 (which also provides a `xen` flag to `_oasis`, and compiles the stubs if `mirage-xen` is present ).

You can use that patch, and have an item such as `- OCAML_VERSION=latest DEPOPTS=mirage-xen` in your `travis.yml` (as another entry in the `matrix` section), this will let travis install `mirage-xen` and build `crc` with MirageOS/Xen support.

To properly test it, there's no way we can convince travis (to start up a Xen virtual machine), but you could write your test cases as a unikernel, outputting to console and look whether it looks sensible.

@yomimono what's your opinion? did you actually execute crc code using your patch on Xen yet?

**Comment by talex5** [comment]
Note that compiling without `-mno-red-zone` will result in a binary that mostly works, but occasionally crashes (if an interrupt occurs while a CRC calculation is taking place). We had this problem with tcpip a while back, and it was hard to track down: https://github.com/mirage/mirage-tcpip/issues/80

(you also need to symlink a copy of the source file, because oasis only compiles each source path once, even if you ask for it to be compiled with different sets of flags)

I don't even remember making my patch, nor why I didn't send a PR for it, but it looks reasonable to me (given we don't have opam support for cross-compiling yet).

**Comment by yomimono** [comment]
Yes, I did execute this code in Xen but it was never heavily in use; I'm totally fine with merging @talex5's patches instead.

**Pull request merged**
