### PR TITLE
Xen

### PR DESCRIPTION
**Pull request by hannesm**
this replaces the ~50 line ML code with 3 lines of shell.  the result on xen is the same

### CODE REVIEW

**Comment by johnelse** [comment]
Do you mean `ml -> sh` ? :)

**Comment by hannesm** [comment]
yes... stupid me.. I amended that commit message

**Comment by hannesm** [comment]
thanks! now a release would be awesome! :)

**Comment by johnelse** [comment]
OK, I'll sort that out :+1:

**Pull request merged**
